### PR TITLE
You fucking bitch boy why did you copy Calypso bot

### PR DESCRIPTION
**Pull request by Dragonizedpizza**

### CODE REVIEW

**Comment by Mad-Ollie** [comment]
thats real

**Comment by Dragonizedpizza** [comment]
> thats real

what

**Comment by NotOliverDev** [comment]
> > thats real
> 
> what

Yeah

**Comment by Dragonizedpizza** [comment]
> > > thats real
> > 
> > 
> > what
> 
> Yeah

its copied you mad man

**Comment by Dragonizedpizza** [comment]
https://github.com/sabattle/CalypsoBot

**Comment by NotOliverDev** [comment]
I know that, this bot is a bad fork of that

And the owner of that say "Open source"🤣🤣🤣

**Comment by Dragonizedpizza** [comment]
> I know that, this bot is a bad fork of that
> 
> And the owner of that say "Open source"🤣🤣🤣

he also says respect license, which is why you can't rob it otherwise everyone would have done it ok

**Comment by customduck** [comment]
Well, as a Moderator of the Development of Calypso. It clearly states that you can use the bot commercially, and to back that up it's on GitHub for a reason, it's not really copying if it's 100% open source..

**Comment by pauldb09** [comment]
Hello, it is not him who copied but GalackQSM
https://discord.com/invite/TwXbSSzmqu

**Comment by Dragonizedpizza** [comment]
its all've you

**Pull request closed without merging**
